### ISSUE TITLE
Update the colour of the Wonder card

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaForAdventurers/bibliotheca-webite#2]
I think the Wonder card gets lost on the Realms feed (https://bibliothecaforloot.com/realms).

Thoughts on updating the black card with a white border to the colourful gradient colour (used in Wonder rarities). 

![image](https://user-images.githubusercontent.com/91049656/133967232-c049cf88-2061-41a8-b6d1-63cb9cc72775.png)

**Comment by ponderingdemocritus** [comment]
Good idea Squid - I will make it happen

**Comment by ponderingdemocritus** [comment]
All done @LordSquiddy
